### ISSUE TITLE
Pip installation is broken

### ISSUE THREAD

**Issue by maxmalysh** [Monero-Monitor/pymonero#2]
```
>>> import pymonero
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/pymonero/__init__.py", line 1, in <module>
    from . import core
  File "/usr/local/lib/python3.5/site-packages/pymonero/core.py", line 2, in <module>
    from . import bitmonerod as _bitmonerod
ImportError: cannot import name 'bitmonerod'

```

Installed via `pip3 install git+https://github.com/Monero-Monitor/pymonero.git`
Python 3.5.1, OS X 10.11. 

Looks like using absolute imports will fix this.

**Comment by bigreddmachine** [comment]
Thanks for the issue. I need to do some work on this package with the new Monero version release anyway, and have been needing to get things working correctly with pip.
